name: ESLint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
